### PR TITLE
fix: local_swift_package relative path resolution

### LINKED ISSUE #363: Local packages do not work with non-root based setups
If you configure the project like the [Vapor example](https://github.com/cgrindel/rules_swift_package_manager/tree/main/examples/vapor_example) and try to depend on a local package from the `Package.swift` like:

```swift
.package(path: "../Path/To/MyPackage"),
```

Then the `swift_dependencies` declaration for `local_swift_package` gets generated like so:

```python
    local_swift_package(
        ...
        path = "../Path/To/MyPackage",
    )
```

When this rule is built it [uses a relative path from the `WORKSPACE`](https://github.com/cgrindel/rules_swift_package_manager/blob/main/swiftpkg/internal/local_swift_package.bzl#L36-L41) since thats what repository contexts allow. This ends up with a failure during build.

The `path` attribute should be consumed relative to the `Package.swift` but generated relative to `WORKSPACE` file.

### PR DESCRIPTION
**Pull request by luispadron**
This fixes the relative path resolution for local_swift_package when the Package.swift is not in the root of the repository.

Closes #363

### CODE REVIEW

**Comment by luispadron** [comment]
Will update the tests in a few

File: gazelle/internal/swift/repo_rule_from_bazel_repo_test.go [hunk 1]
```diff
@@ -58,12 +60,34 @@ func TestRepoRuleFromBazelRepo(t *testing.T) {
...
-		actual, err := swift.RepoRuleFromBazelRepo(br, diBasename, pkgDir)
+		actual, err := swift.RepoRuleFromBazelRepo(br, diBasename, pkgDir, repoDir)
 		assert.NoError(t, err)
 
 		expected := rule.NewRule(swift.LocalSwiftPkgRuleKind, repoName)
 		expected.SetAttr("path", relLocalPkgDir)
 		expected.SetAttr("dependencies_index", fmt.Sprintf("@//:%s", diBasename))
 		assert.Equal(t, expected, actual)
 	})
+	t.Run("without pin (local Swift package with relative path)", func(t *testing.T) {
```
Comment (luispadron) [inline gazelle/internal/swift/repo_rule_from_bazel_repo_test.go:71]: Added this test to assert the fixed behavior
